language: c
compiler: gcc

os:
  - osx
  - linux

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5-dev
      - lua5.2
      - liblua5.2-dev

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then travis_retry brew update; travis_retry brew install lua pcre python3; fi

env:
  matrix:
    - OPTS=""
    - OPTS="--enable-lua"
    - OPTS="--enable-python"
    - OPTS="--enable-lua --enable-python"

script: ./configure --enable-version --enable-symlink --enable-getaddrinfo --enable-atcp --enable-gmcp --enable-option102 $OPTS && make
